name: "Extract Semver from Tag"
description: "Extracts semantic version (including pre-release) from a tag and outputs it"
runs:
  using: "composite"
  steps:
    - name: Extract semver
      shell: bash
      run: |
        # GITHUB_REF example: refs/tags/functions/go/set-namespace/v2.0.0
        REF="${GITHUB_REF}"
        TAG="${REF#refs/tags/}"   # remove 'refs/tags/' prefix
        VERSION="${TAG##*/}"      # get last part after last slash

        # Validate semver with optional pre-release and build metadata
        if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Error: Tag '$VERSION' is not a valid semver" >&2
          exit 1
        fi
outputs:
  version:
    description: "The extracted semantic version from the tag"
